### ISSUE TITLE
孤雙引號愛改用有方向性的 ‘ 佮 “

### ISSUE THREAD

**Issue by a8568730** [i3thuan5/kau3-tian2_iong7-ji7#33]
https://github.com/Sui-Siann-Dataset/Sui-Siann-Dataset/issues/113#issuecomment-458780636
> 半形引號有4種
> 
> 孤	雙
> 有方向	`‘a’`	`“a”`
> 無方向	`'a'`	`"a"`
> 我查英語ê慣勢，攏是用有方向--ê
>

**Comment by sih4sing5hong5** [comment]
Sui-siann

  |  漢字 | 羅馬字 | 分詞
-- | -- | -- | -- 
   | 》 | ” | 》｜”
  | 《 | “ | 《｜“
  | 』 | ’ | 』｜’
  | 『 | ‘ | 『｜‘
  | 」 | ” | 」｜”
  | 「 | “ | 「｜“

**Comment by sih4sing5hong5** [comment]
https://github.com/Sui-Siann-Dataset/Sui-Siann-Dataset/issues/148#issuecomment-465390660
